# Generated by Django 2.2.16 on 2022-02-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_message_recaptcha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
